project:
  type: website
  output-dir: docs
  preview:
    port: 7778

website:
  title: "SHAIK M. JANI BASHA"
  navbar:
    #pinned: true
    right:
      - icon: puzzle
        text: "Product Management"
        menu:
          - href: projects.qmd
            text: "Case Studies"
          - href: frameworks.qmd
            text: "Frameworks"
          - href: tutorials.qmd
            text: "Tutorials"
      - icon: robot
        href: projects.qmd
        text: AI/ML Projects
      - icon: newspaper
        href: projects.qmd
        text: Blog
      - icon: file-person
        href: index.qmd
        text: About
      
format:
  html:
    grid:
      body-width: 900px
    theme: 
      light: [simplex, styles.scss]
      dark: [cosmo, styles-dark.scss]
    highlight-style: a11y-dark
    #mainfont: Inter
    code-copy: true
    code-overflow: wrap
    #linestretch: 1.5

execute:
  freeze: auto
