project:
  type: website
  output-dir: docs
  preview:
    port: 7778

website:
  title: "SHAIK M. JANI BASHA"
  navbar:
    #pinned: true
    right:
      - text: "Product Management"
        menu:
          - href: projects.qmd
            text: "CASE STUDIES"
          - href: frameworks.qmd
            text: "Frameworks"
          - href: tutorials.qmd
            text: "Tutorials"
      - href: projects.qmd
        text: AI/ML Projects
      - href: index.qmd
        text: About
      
format:
  html:
    grid:
      body-width: 900px
    theme: [cosmo, styles.scss]
    highlight-style: a11y-dark
    mainfont: Roboto
    code-copy: true
    code-overflow: wrap
    #linestretch: 1.5

execute:
  freeze: auto
