project:
  type: website
  output-dir: docs
  preview:
    port: 7778

website:
  title: "SHAIK M. JANI BASHA"
  navbar:
    #pinned: true
    right:
      - text: "PRODUCT MANAGEMENT"
        menu:
          - href: projects.qmd
            text: "CASE STUDIES"
          - href: frameworks.qmd
            text: "Frameworks"
          - href: tutorials.qmd
            text: "Tutorials"
      - href: projects.qmd
        text: AI/ML PROJECTS
      - href: index.qmd
        text: ABOUT
      
format:
  html:
    theme: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: Barlow
    code-copy: true
    code-overflow: wrap
    #linestretch: 1.5

execute:
  freeze: auto
